name: Hello World
description: Outputs 'Hello <name>, hello world' where name can be supplied as an arg
author: Ama Asare, DPD
requirements:
  - bash
configuration:
  properties:
    helloname:
      type: string