# Default pipeline from cli
steps:
  - label: ':woman-lifting-weights: kickoff fitness check'
    plugins:
      - https://github.com/amasare/dpd-plugin-support: 
          pluginsource: https://github.com/amasare/buildkite-plugin-hello-world
    agents: 
      queue: 'base-agent'