# Default pipeline from cli
steps:
  - label: ':woman-lifting-weights: kickoff fitness check'
    plugins:
      - https://github.com/amasare/dpd-plugin-fitness-function: ~
    agents: 
      queue: 'base-agent'